name: synchronize

on:
  workflow_dispatch:
  repository_dispatch:
    types:
      - synchronize

jobs:
  synchronize:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Clean old files except for .github folder
        run: |
          git rm \* ':!.github'
          git clean -fxd
      
      - name: Configure git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Clone
        run: git clone https://github.com/navigarejs/framework.git /tmp/framework

      - name: Copy Laravel package
        run: mv -v /tmp/framework/packages/laravel/* .

      - name: Read version
        run: |
          version=$(jq -r ".version" package.json)
          echo "VERSION=${version}" >> $GITHUB_ENV

      - name: Delete obsolete files
        run: |
          rm package.json
          rm release.config.cjs

      - name: Add changes
        run: git add -A

      - name: Set message
        run: |
          echo "MESSAGE=chore(release): v${{ env.VERSION }} [skip ci]" >> $GITHUB_ENV

      - name: Commit changes
        run: git commit -m "${{ env.MESSAGE }}" || true

      - name: Tag change
        run: git tag -a "v${{ env.VERSION }}" -m "v${{ env.VERSION }}"

      - name: Push back changes
        run: |
          git push --force --tags
          git push --force

        
